/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhunior
 */
public class frmRegistroCandidato2 extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistroCandidato2
     */
    public frmRegistroCandidato2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCertificaciones = new javax.swing.JTextField();
        lblHabilidades = new javax.swing.JLabel();
        lblCertificaciones = new javax.swing.JLabel();
        lblImagenRegistro = new javax.swing.JLabel();
        lblRegistro = new javax.swing.JLabel();
        lblExperiencia = new javax.swing.JLabel();
        txtExperiencia = new javax.swing.JTextField();
        lblObjetivo = new javax.swing.JLabel();
        btnVolver2 = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        lblContratoFirmado = new javax.swing.JLabel();
        txtHabilidades = new javax.swing.JPasswordField();
        txtObjetivo = new javax.swing.JPasswordField();
        txtContratoFirmado = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCertificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertificacionesActionPerformed(evt);
            }
        });

        lblHabilidades.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        lblHabilidades.setText("HABILIDADES");

        lblCertificaciones.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        lblCertificaciones.setText("CERTIFICACIONES");

        lblImagenRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgRegistro.png"))); // NOI18N

        lblRegistro.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        lblRegistro.setText("INFORMACIÓN PROFESIONAL");

        lblExperiencia.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        lblExperiencia.setText("EXPERIENCIA");

        lblObjetivo.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        lblObjetivo.setText("OBJETIVO");

        btnVolver2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnVolver2.setText("Volver");
        btnVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver2ActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblContratoFirmado.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        lblContratoFirmado.setText("CONTRATO FIRMADO");

        txtHabilidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHabilidadesActionPerformed(evt);
            }
        });

        txtObjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObjetivoActionPerformed(evt);
            }
        });

        txtContratoFirmado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContratoFirmadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegistro)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblContratoFirmado)
                                .addGap(36, 36, 36)
                                .addComponent(txtContratoFirmado, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblObjetivo)
                                    .addComponent(lblExperiencia)
                                    .addComponent(lblHabilidades)
                                    .addComponent(lblCertificaciones))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCertificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                        .addComponent(txtHabilidades)
                                        .addComponent(txtExperiencia))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(lblImagenRegistro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnRegistrar)
                        .addGap(54, 54, 54)
                        .addComponent(btnVolver2)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblRegistro)
                .addGap(12, 12, 12)
                .addComponent(lblImagenRegistro)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExperiencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCertificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCertificaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHabilidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHabilidades))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObjetivo)
                    .addComponent(txtObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContratoFirmado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContratoFirmado))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnVolver2))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCertificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertificacionesActionPerformed

    private void btnVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolver2ActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtHabilidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHabilidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHabilidadesActionPerformed

    private void txtObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObjetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObjetivoActionPerformed

    private void txtContratoFirmadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContratoFirmadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContratoFirmadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroCandidato2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroCandidato2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroCandidato2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroCandidato2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistroCandidato2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JButton btnVolver2;
    private javax.swing.JLabel lblCertificaciones;
    private javax.swing.JLabel lblContratoFirmado;
    private javax.swing.JLabel lblExperiencia;
    private javax.swing.JLabel lblHabilidades;
    private javax.swing.JLabel lblImagenRegistro;
    private javax.swing.JLabel lblObjetivo;
    private javax.swing.JLabel lblRegistro;
    public javax.swing.JTextField txtCertificaciones;
    public javax.swing.JPasswordField txtContratoFirmado;
    private javax.swing.JTextField txtExperiencia;
    public javax.swing.JPasswordField txtHabilidades;
    public javax.swing.JPasswordField txtObjetivo;
    // End of variables declaration//GEN-END:variables
}
